/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roomscheduler;

import java.sql.Date;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author chaturvedsumanth
 */
public class MainFrame extends javax.swing.JDialog {

    /**
     * Creates new form MainFrame
     */
    
    private DBConnection dbconnection;
    private Dates dates;
    private Faculty faculty;
    private ReservationQueries reservationqueries;
    private RoomQueries roomqueries;
    private WaitlistQueries waitlistqueries;
    
    private String minroom;
    
    public MainFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.dbconnection= new DBConnection();
        this.dates=new Dates(this.dbconnection);
        this.faculty=new Faculty(this.dbconnection);
        this.reservationqueries=new ReservationQueries(this.dbconnection);
        this.roomqueries=new RoomQueries(this.dbconnection);
        this.waitlistqueries=new WaitlistQueries(this.dbconnection);
        
        this.minroom="";
        
        this.setComboBoxModels();
        
        
    }
    
    private void setComboBoxModels(){
        
        this.reserveFacultyComboBox.setModel(new DefaultComboBoxModel(this.faculty.getAllFaculty().toArray()));
        this.reserveDateComboBox.setModel(new DefaultComboBoxModel(this.dates.getAllDates().toArray()));
        this.dateCombobox.setModel(new DefaultComboBoxModel(this.dates.getAllDates().toArray()));
        this.cancelFacultyComboBox.setModel(new DefaultComboBoxModel(this.faculty.getAllFaculty().toArray()));
        this.cancelDateComboBox.setModel(new DefaultComboBoxModel(this.dates.getAllDates().toArray()));
        this.statusfacultyFacultyComboBox.setModel(new DefaultComboBoxModel(this.faculty.getAllFaculty().toArray()));
        this.dropRoomComboBox.setModel(new DefaultComboBoxModel(this.roomqueries.getAllRoomsNames().toArray()));
        
    }
    
    private boolean reserveRoom(String facultyselected,Date dateselected,int seatsentered,int option){
        ArrayList<RoomEntry> roomsreservedbydate=this.reservationqueries.getRoomsReservedByDate(dateselected);
        ArrayList<RoomEntry> allPossibleRooms=this.roomqueries.getAllPossibleRooms();
        
        for(int i=allPossibleRooms.size()-1;i>=0;i--){      
            if(seatsentered > allPossibleRooms.get(i).getSeats()){
                allPossibleRooms.remove(i);
            }
        }
        
        for(int i=roomsreservedbydate.size()-1;i>=0;i--){
            for(int j=allPossibleRooms.size()-1;j>=0;j--)
            if(allPossibleRooms.get(j).getName().equals(roomsreservedbydate.get(i).getName())){
                allPossibleRooms.remove(j);
            }
        }
        
        if(allPossibleRooms.isEmpty()){
            if(option==0){
                WaitlistEntry waitlistentry=new WaitlistEntry(facultyselected,dateselected,seatsentered,new Timestamp(Calendar.getInstance().getTime().getTime()));
                this.waitlistqueries.addWaitlistEntry(waitlistentry);
            }
            
                    
            return false;
        }
        
        int minseats=allPossibleRooms.get(0).getSeats();
        this.minroom=allPossibleRooms.get(0).getName();
        for(int i=0;i<allPossibleRooms.size();i++){
            if(allPossibleRooms.get(i).getSeats() < minseats){
                minseats=allPossibleRooms.get(i).getSeats();
                this.minroom=allPossibleRooms.get(i).getName();
            }
        }
        
        ReservationEntry reservationentry=new ReservationEntry(facultyselected,this.minroom,dateselected,minseats,new Timestamp(Calendar.getInstance().getTime().getTime()));
        this.reservationqueries.addReservationEntry(reservationentry);
        
        return true;
     
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomSchedulerLabel = new java.awt.Label();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        facultyNameLabel = new java.awt.Label();
        facultyNameTextField = new java.awt.TextField();
        addFacultySubmitButton = new java.awt.Button();
        statusBarAddFaculty = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        reserveSelectFacultyLabel = new java.awt.Label();
        reserveSelectDateLabel = new java.awt.Label();
        reserveRoomSeatsLabel = new java.awt.Label();
        reserveSubmitButton = new java.awt.Button();
        reserveStatusBar = new java.awt.Label();
        reserveFacultyComboBox = new javax.swing.JComboBox<>();
        reserveDateComboBox = new javax.swing.JComboBox<>();
        reserveRoomSeatsTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        dateCombobox = new javax.swing.JComboBox<>();
        dateRBDButoon = new javax.swing.JButton();
        dateStatusLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dateStatusArea = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        waitlistLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        waitlistStatusArea = new javax.swing.JTextArea();
        waitlistGetButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        roomNameLabel = new javax.swing.JLabel();
        roomNameTextField = new javax.swing.JTextField();
        roomSeatsLabel = new javax.swing.JLabel();
        roomSeatsTextField = new javax.swing.JTextField();
        roomSubmitButton = new javax.swing.JButton();
        roomStatusLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        roomStatusArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adddateLabel = new javax.swing.JLabel();
        adddateSubmitButton = new javax.swing.JButton();
        adddateStatusLabel = new javax.swing.JLabel();
        adddateStatusBar = new javax.swing.JLabel();
        adddateSpinner = new javax.swing.JSpinner();
        adddateFormatLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        cancelFacultyLabel = new javax.swing.JLabel();
        cancelDateLabel = new javax.swing.JLabel();
        cancelFacultyComboBox = new javax.swing.JComboBox<>();
        cancelDateComboBox = new javax.swing.JComboBox<>();
        cancelSubmitButton = new javax.swing.JButton();
        cancelStatusLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cancelStatusArea = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        statusfacultyFacultyLabel = new javax.swing.JLabel();
        statusfacultyFacultyComboBox = new javax.swing.JComboBox<>();
        statusfacultyStatusLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        statusfacultyStatusArea = new javax.swing.JTextArea();
        statusfacultySubmitButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        dropRoomLabel = new javax.swing.JLabel();
        dropRoomComboBox = new javax.swing.JComboBox<>();
        dropRoomSubmitButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        dropRoomStatusArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roomSchedulerLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        roomSchedulerLabel.setForeground(new java.awt.Color(153, 0, 255));
        roomSchedulerLabel.setText("Room Scheduler");

        jTabbedPane1.setForeground(new java.awt.Color(51, 255, 51));

        facultyNameLabel.setForeground(new java.awt.Color(255, 51, 51));
        facultyNameLabel.setText("Faculty Name:");

        facultyNameTextField.setForeground(new java.awt.Color(0, 0, 255));
        facultyNameTextField.setText("Enter Name");

        addFacultySubmitButton.setBackground(new java.awt.Color(0, 0, 0));
        addFacultySubmitButton.setForeground(new java.awt.Color(0, 255, 0));
        addFacultySubmitButton.setLabel("Submit");
        addFacultySubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultySubmitButtonActionPerformed(evt);
            }
        });

        statusBarAddFaculty.setForeground(new java.awt.Color(255, 0, 0));
        statusBarAddFaculty.setText("Status:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addFacultySubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(facultyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(facultyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(statusBarAddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(800, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(facultyNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(facultyNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(addFacultySubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBarAddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Faculty", jPanel1);

        reserveSelectFacultyLabel.setForeground(new java.awt.Color(255, 0, 153));
        reserveSelectFacultyLabel.setText("Select Faculty:");

        reserveSelectDateLabel.setForeground(new java.awt.Color(255, 0, 153));
        reserveSelectDateLabel.setText("Select Date:");

        reserveRoomSeatsLabel.setForeground(new java.awt.Color(255, 0, 153));
        reserveRoomSeatsLabel.setText("Room Seats:");

        reserveSubmitButton.setForeground(new java.awt.Color(255, 51, 0));
        reserveSubmitButton.setLabel("Submit");
        reserveSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSubmitButtonActionPerformed(evt);
            }
        });

        reserveStatusBar.setForeground(new java.awt.Color(0, 102, 102));
        reserveStatusBar.setText("Status:");

        reserveFacultyComboBox.setForeground(new java.awt.Color(0, 51, 204));
        reserveFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        reserveDateComboBox.setForeground(new java.awt.Color(0, 51, 204));
        reserveDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        reserveRoomSeatsTextField.setForeground(new java.awt.Color(0, 51, 255));
        reserveRoomSeatsTextField.setText("Enter Seats");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(reserveStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(reserveSelectDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reserveSelectFacultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reserveRoomSeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(reserveFacultyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(reserveRoomSeatsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                            .addComponent(reserveSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(992, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveSelectFacultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveSelectDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reserveRoomSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveRoomSeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(reserveSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reserveStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reserve Room", jPanel2);

        dateLabel.setForeground(new java.awt.Color(0, 153, 153));
        dateLabel.setText("Select Date:");

        dateCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dateRBDButoon.setForeground(new java.awt.Color(204, 0, 204));
        dateRBDButoon.setText("Get Reservations by Date");
        dateRBDButoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateRBDButoonActionPerformed(evt);
            }
        });

        dateStatusLabel.setForeground(new java.awt.Color(0, 153, 0));
        dateStatusLabel.setText("Status:");

        dateStatusArea.setColumns(20);
        dateStatusArea.setRows(5);
        dateStatusArea.setText("\n");
        jScrollPane1.setViewportView(dateStatusArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateStatusLabel)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(dateRBDButoon, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(811, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateRBDButoon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Status Reservations by Date", jPanel3);

        waitlistLabel.setForeground(new java.awt.Color(0, 0, 255));
        waitlistLabel.setText("Waitlist:");

        waitlistStatusArea.setColumns(20);
        waitlistStatusArea.setRows(5);
        jScrollPane2.setViewportView(waitlistStatusArea);

        waitlistGetButton.setBackground(new java.awt.Color(0, 0, 0));
        waitlistGetButton.setForeground(new java.awt.Color(255, 204, 0));
        waitlistGetButton.setText("Get Waitlist");
        waitlistGetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitlistGetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 815, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(waitlistLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(waitlistGetButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(waitlistLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waitlistGetButton)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Status Waiting List", jPanel5);

        roomNameLabel.setForeground(new java.awt.Color(102, 0, 51));
        roomNameLabel.setText("Room Name:");

        roomNameTextField.setForeground(new java.awt.Color(0, 0, 255));
        roomNameTextField.setText("Enter Name");

        roomSeatsLabel.setForeground(new java.awt.Color(153, 0, 153));
        roomSeatsLabel.setText("Room Seats:");

        roomSeatsTextField.setForeground(new java.awt.Color(0, 0, 255));
        roomSeatsTextField.setText("Enter Seats");

        roomSubmitButton.setForeground(new java.awt.Color(0, 153, 0));
        roomSubmitButton.setText("Submit");
        roomSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomSubmitButtonActionPerformed(evt);
            }
        });

        roomStatusLabel.setForeground(new java.awt.Color(255, 0, 0));
        roomStatusLabel.setText("Status:");

        roomStatusArea.setColumns(20);
        roomStatusArea.setRows(5);
        jScrollPane3.setViewportView(roomStatusArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomNameLabel)
                            .addComponent(roomSeatsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roomNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(roomSeatsTextField)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(roomSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(roomStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(647, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomNameTextField)
                    .addComponent(roomNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomSeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(roomSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(roomStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Room", jPanel4);

        adddateLabel.setForeground(new java.awt.Color(153, 0, 51));
        adddateLabel.setText("Date:");

        adddateSubmitButton.setForeground(new java.awt.Color(204, 204, 0));
        adddateSubmitButton.setText("Submit");
        adddateSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddateSubmitButtonActionPerformed(evt);
            }
        });

        adddateStatusLabel.setForeground(new java.awt.Color(0, 102, 102));
        adddateStatusLabel.setText("Status:");

        adddateStatusBar.setText("Entry will be displayed here");

        adddateSpinner.setModel(new javax.swing.SpinnerDateModel());

        adddateFormatLabel.setForeground(new java.awt.Color(0, 0, 255));
        adddateFormatLabel.setText("Format: DD/MM/YY");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(adddateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adddateSubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adddateSpinner))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adddateFormatLabel)
                        .addGap(0, 622, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(adddateStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adddateStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(256, 256, 256))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adddateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adddateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adddateFormatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adddateSubmitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adddateStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adddateStatusBar))
                        .addGap(18, 18, 18)))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Date", jPanel6);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelFacultyLabel.setForeground(new java.awt.Color(255, 51, 51));
        cancelFacultyLabel.setText("Faculty:");

        cancelDateLabel.setForeground(new java.awt.Color(102, 0, 102));
        cancelDateLabel.setText("Date:");

        cancelFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelSubmitButton.setForeground(new java.awt.Color(204, 204, 0));
        cancelSubmitButton.setText("Submit");
        cancelSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSubmitButtonActionPerformed(evt);
            }
        });

        cancelStatusLabel.setForeground(new java.awt.Color(0, 0, 204));
        cancelStatusLabel.setText("Status:");

        cancelStatusArea.setColumns(20);
        cancelStatusArea.setRows(5);
        jScrollPane4.setViewportView(cancelStatusArea);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelDateLabel)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(cancelSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cancelStatusLabel)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelFacultyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cancelDateComboBox, 0, 137, Short.MAX_VALUE)
                                    .addComponent(cancelFacultyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(766, 766, 766))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelFacultyLabel)
                        .addComponent(cancelFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelDateLabel)
                            .addComponent(cancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(cancelSubmitButton)
                .addGap(28, 28, 28)
                .addComponent(cancelStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancel Reservation", jPanel7);

        statusfacultyFacultyLabel.setForeground(new java.awt.Color(204, 0, 204));
        statusfacultyFacultyLabel.setText("Faculty:");

        statusfacultyFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        statusfacultyStatusLabel.setForeground(new java.awt.Color(102, 0, 102));
        statusfacultyStatusLabel.setText("Status:");

        statusfacultyStatusArea.setColumns(20);
        statusfacultyStatusArea.setRows(5);
        jScrollPane5.setViewportView(statusfacultyStatusArea);

        statusfacultySubmitButton.setForeground(new java.awt.Color(187, 130, 11));
        statusfacultySubmitButton.setText("Submit");
        statusfacultySubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusfacultySubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusfacultyStatusLabel)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(statusfacultyFacultyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusfacultyFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(statusfacultySubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(430, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusfacultyFacultyLabel)
                    .addComponent(statusfacultyFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusfacultySubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusfacultyStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Status Faculty Member", jPanel8);

        dropRoomLabel.setText("Room Name:");

        dropRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dropRoomSubmitButton.setText("Submit");
        dropRoomSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropRoomSubmitButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Status:");

        dropRoomStatusArea.setColumns(20);
        dropRoomStatusArea.setRows(5);
        jScrollPane6.setViewportView(dropRoomStatusArea);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dropRoomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(dropRoomSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(529, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropRoomLabel)
                    .addComponent(dropRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dropRoomSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel3.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Drop Room", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(roomSchedulerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomSchedulerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adddateSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddateSubmitButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(this.adddateSpinner.getValue());
        Date day = Date.valueOf(spinnerValue);

        this.dates.addDate(day);
        this.adddateStatusBar.setText(day.toString()+" was sucessfully added to the database");
        this.setComboBoxModels();
    }//GEN-LAST:event_adddateSubmitButtonActionPerformed

    private void roomSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomSubmitButtonActionPerformed
        // TODO add your handling code here:
        String roomName=this.roomNameTextField.getText();
        int roomSeats=Integer.parseInt(this.roomSeatsTextField.getText());
        String entries="Room added!\n";

        RoomEntry roomentry=new RoomEntry(roomName,roomSeats);
        this.roomqueries.addRoom(roomentry);

        ArrayList <WaitlistEntry> waitlist= this.waitlistqueries.getWaitlistDTR();
        for(int i=0;i<waitlist.size();i++){
            if(this.reserveRoom(waitlist.get(i).getFaculty(), waitlist.get(i).getDate(), waitlist.get(i).getSeats(), 1)){
                entries=entries+waitlist.get(i).getFaculty()+" is removed from waitlist and the reservation made in Room "+this.minroom+" on "+waitlist.get(i).getDate().toString()+" for "+waitlist.get(i).getSeats()+" seats"+"\n";
                this.waitlistqueries.deleteWaitlistEntry(waitlist.get(i));
            }
        }

        this.roomStatusArea.setText(entries);

    }//GEN-LAST:event_roomSubmitButtonActionPerformed

    private void waitlistGetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitlistGetButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<WaitlistEntry> waitlist=this.waitlistqueries.getWaitlistDTR();
        String entries="";

        for(int i=0;i<waitlist.size();i++){
            entries=entries+waitlist.get(i).getFaculty()+" is waitlisted at "+waitlist.get(i).getDate().toString()+" for "+waitlist.get(i).getSeats()+" seats"+"\n";
        }
        this.waitlistStatusArea.setText(entries);
    }//GEN-LAST:event_waitlistGetButtonActionPerformed

    private void dateRBDButoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateRBDButoonActionPerformed
        // TODO add your handling code here:
        Date dateselected= (Date) this.dateCombobox.getSelectedItem();
        ArrayList <ReservationEntry> RBD= this.reservationqueries.getReservationsByDate(dateselected);
        String entries="";

        for(int i=0;i<RBD.size();i++){
            if(i==RBD.size()-1){
                entries=entries+RBD.get(i).getFaculty()+" reserved room "+RBD.get(i).getRoom();
            }
            else{
                entries=entries+RBD.get(i).getFaculty()+" reserved room "+RBD.get(i).getRoom()+"\n";
            }

        }
        this.dateStatusArea.setText(entries);
        this.setComboBoxModels();
    }//GEN-LAST:event_dateRBDButoonActionPerformed

    private void reserveSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSubmitButtonActionPerformed
        // TODO add your handling code here:
        String facultyselected=this.reserveFacultyComboBox.getSelectedItem().toString();
        Date dateselected=(Date) this.reserveDateComboBox.getSelectedItem();
        int seatsentered=Integer.parseInt(this.reserveRoomSeatsTextField.getText());

        if(reserveRoom(facultyselected,dateselected,seatsentered,0)){
            this.reserveStatusBar.setText("Status: "+"Reservation Sucessful "+"in Room "+this.minroom);
        }
        else{
            this.reserveStatusBar.setText("Status: "+"Reservation Unsucessful but added to Waitlist");
        }
    }//GEN-LAST:event_reserveSubmitButtonActionPerformed

    private void addFacultySubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultySubmitButtonActionPerformed
        // TODO add your handling code here:
        String name=this.facultyNameTextField.getText();
        this.statusBarAddFaculty.setText("Status:"+this.faculty.addFaculty(name)+" ("+name+")");
        this.setComboBoxModels();
    }//GEN-LAST:event_addFacultySubmitButtonActionPerformed

    private void cancelSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSubmitButtonActionPerformed
        // TODO add your handling code here:
        String faculty=this.cancelFacultyComboBox.getSelectedItem().toString();
        Date date=(Date) this.cancelDateComboBox.getSelectedItem();
        
        int cntr=this.reservationqueries.deleteReservation(new ReservationEntry(faculty,date));
        int cntw=this.waitlistqueries.deleteWaitlistEntry(new WaitlistEntry(faculty,date));
        
        if(cntr==0 && cntw==0){
            this.cancelStatusArea.setText("No reservation found!");
        }
        else{
        
            String entries="Reservation Cancelled\n";
            ArrayList <WaitlistEntry> waitlist=this.waitlistqueries.getWaitlistByDateR(date);
            
            for(int i=0;i<waitlist.size();i++){
                if(this.reserveRoom(waitlist.get(i).getFaculty(), waitlist.get(i).getDate(), waitlist.get(i).getSeats(),0)){
                    this.waitlistqueries.deleteWaitlistEntry(waitlist.get(i));
                    entries=entries+waitlist.get(i).getFaculty()+" was removed from waitlist and added to the reservations in Room "+this.minroom+"\n";
                }
            }
            
            this.cancelStatusArea.setText(entries);
        }
        
    }//GEN-LAST:event_cancelSubmitButtonActionPerformed

    private void statusfacultySubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusfacultySubmitButtonActionPerformed
        // TODO add your handling code here:
        String faculty=this.statusfacultyFacultyComboBox.getSelectedItem().toString();
        ArrayList <ReservationEntry> reservations=this.reservationqueries.getReservationsByFaculty(faculty);
        ArrayList <WaitlistEntry> waitlist=this.waitlistqueries.getWaitlistByFaculty(faculty);
        
        String entriesr="Reservations:\n";
        String entriesw="Waitlist:\n";
        
        for(int i=0;i<reservations.size();i++){
            entriesr=entriesr+"Room "+reservations.get(i).getRoom()+" for "+reservations.get(i).getDate().toString()+"\n";
        }
        
        for(int i=0;i<waitlist.size();i++){
            entriesw=entriesw+"For "+waitlist.get(i).getDate().toString()+"\n";
        }
        
        this.statusfacultyStatusArea.setText(entriesr+"\n"+entriesw);
    }//GEN-LAST:event_statusfacultySubmitButtonActionPerformed

    private void dropRoomSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropRoomSubmitButtonActionPerformed
        // TODO add your handling code here:
        String roomName=this.dropRoomComboBox.getSelectedItem().toString();
        this.roomqueries.dropRoom(roomName);
        
        ArrayList<ReservationEntry> reservations=this.reservationqueries.getReservationsByRoom(roomName);
        ArrayList<String> faculties=new ArrayList<>();
        
        for(int i=0;i<reservations.size();i++){
            WaitlistEntry waitlistentry=new WaitlistEntry(reservations.get(i).getFaculty(),reservations.get(i).getDate(),reservations.get(i).getSeats(),reservations.get(i).getTimestamp());
            this.waitlistqueries.addWaitlistEntry(waitlistentry);
            
            faculties.add(reservations.get(i).getFaculty());
            this.reservationqueries.deleteReservation(reservations.get(i));
        }
        
        
        ArrayList<WaitlistEntry> waitlist=this.waitlistqueries.getWaitlistDTR();
        String entries="";
       
        for(int i=0;i<waitlist.size();i++){
            if(this.reserveRoom(waitlist.get(i).getFaculty(), waitlist.get(i).getDate(), waitlist.get(i).getSeats(), 1)){
                if(faculties.contains(waitlist.get(i).getFaculty())){
                    entries=entries+waitlist.get(i).getFaculty()+" was reserved a New Room in "+this.minroom+" on "+waitlist.get(i).getDate().toString()+"\n";
                }
                else{
                    
                    entries=entries+waitlist.get(i).getFaculty()+" was removed from the waitlist and was reserved a Room in "+this.minroom+" on "+waitlist.get(i).getDate().toString()+"\n";
                }
                
                this.waitlistqueries.deleteWaitlistEntry(new WaitlistEntry(waitlist.get(i).getFaculty(),waitlist.get(i).getDate()));
                
            }
            else{
            
                entries=entries+waitlist.get(i).getFaculty()+" was added to the waitlist for "+waitlist.get(i).getSeats()+" seats on "+waitlist.get(i).getDate().toString()+"\n";
            }
        }
        
        this.dropRoomStatusArea.setText(entries);
        this.setComboBoxModels();
    }//GEN-LAST:event_dropRoomSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame dialog = new MainFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addFacultySubmitButton;
    private javax.swing.JLabel adddateFormatLabel;
    private javax.swing.JLabel adddateLabel;
    private javax.swing.JSpinner adddateSpinner;
    private javax.swing.JLabel adddateStatusBar;
    private javax.swing.JLabel adddateStatusLabel;
    private javax.swing.JButton adddateSubmitButton;
    private javax.swing.JComboBox<String> cancelDateComboBox;
    private javax.swing.JLabel cancelDateLabel;
    private javax.swing.JComboBox<String> cancelFacultyComboBox;
    private javax.swing.JLabel cancelFacultyLabel;
    private javax.swing.JTextArea cancelStatusArea;
    private javax.swing.JLabel cancelStatusLabel;
    private javax.swing.JButton cancelSubmitButton;
    private javax.swing.JComboBox<String> dateCombobox;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton dateRBDButoon;
    private javax.swing.JTextArea dateStatusArea;
    private javax.swing.JLabel dateStatusLabel;
    private javax.swing.JComboBox<String> dropRoomComboBox;
    private javax.swing.JLabel dropRoomLabel;
    private javax.swing.JTextArea dropRoomStatusArea;
    private javax.swing.JButton dropRoomSubmitButton;
    private java.awt.Label facultyNameLabel;
    private java.awt.TextField facultyNameTextField;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> reserveDateComboBox;
    private javax.swing.JComboBox<String> reserveFacultyComboBox;
    private java.awt.Label reserveRoomSeatsLabel;
    private javax.swing.JTextField reserveRoomSeatsTextField;
    private java.awt.Label reserveSelectDateLabel;
    private java.awt.Label reserveSelectFacultyLabel;
    private java.awt.Label reserveStatusBar;
    private java.awt.Button reserveSubmitButton;
    private javax.swing.JLabel roomNameLabel;
    private javax.swing.JTextField roomNameTextField;
    private java.awt.Label roomSchedulerLabel;
    private javax.swing.JLabel roomSeatsLabel;
    private javax.swing.JTextField roomSeatsTextField;
    private javax.swing.JTextArea roomStatusArea;
    private javax.swing.JLabel roomStatusLabel;
    private javax.swing.JButton roomSubmitButton;
    private java.awt.Label statusBarAddFaculty;
    private javax.swing.JComboBox<String> statusfacultyFacultyComboBox;
    private javax.swing.JLabel statusfacultyFacultyLabel;
    private javax.swing.JTextArea statusfacultyStatusArea;
    private javax.swing.JLabel statusfacultyStatusLabel;
    private javax.swing.JButton statusfacultySubmitButton;
    private javax.swing.JButton waitlistGetButton;
    private javax.swing.JLabel waitlistLabel;
    private javax.swing.JTextArea waitlistStatusArea;
    // End of variables declaration//GEN-END:variables
}
